Algoritmo "Múltiplos de 2"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Cálculo dos múltiplos de 2 de 1 a 100
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/11/2022
Var
// Seção de Declarações das variáveis
j : INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para j de 1 ate 100 faca
     se (j % 2 = 0) entao
        escreval(j)
     fimse
fimpara
Fimalgoritmo